media:
  input: public/img
  output: /img

content:
  - name: fun_facts
    label: facts
    type: file
    path: _data/fun_facts.json
    list: true

  - name: products
    label: Products
    type: file
    path: _data/products.json
    fields:
      - name: products
        label: Products
        type: object
        list: true
        fields:
          - { name: src, label: Source, type: image }
          - { name: text, label: Text, type: string }